// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Announcement
{
    public int AnnouncementId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string AnnouncementType { get; set; }

    public int AuthorId { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsFeatured { get; set; }

    public virtual User Author { get; set; }
}