// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponCode { get; set; }

    public string Description { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public decimal? MinimumAmount { get; set; }

    public int? MaxUsageCount { get; set; }

    public int? CurrentUsageCount { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidUntil { get; set; }

    public bool? IsActive { get; set; }

    public int CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}