// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class CourseReview
{
    public int ReviewId { get; set; }

    public int CourseId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string ReviewTitle { get; set; }

    public string ReviewText { get; set; }

    public DateTime? ReviewDate { get; set; }

    public bool? IsPublished { get; set; }

    public int? HelpfulVotes { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}