// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Forum
{
    public int PostId { get; set; }

    public int CourseId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime? PostDate { get; set; }

    public DateTime? LastReplyDate { get; set; }

    public int? ReplyCount { get; set; }

    public bool? IsSticky { get; set; }

    public bool? IsClosed { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<ForumReply> ForumReplies { get; set; } = new List<ForumReply>();

    public virtual User User { get; set; }
}