// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ForumReply
{
    public int ReplyId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTime? ReplyDate { get; set; }

    public int? ParentReplyId { get; set; }

    public bool? IsInstructorReply { get; set; }

    public virtual ICollection<ForumReply> InverseParentReply { get; set; } = new List<ForumReply>();

    public virtual ForumReply ParentReply { get; set; }

    public virtual Forum Post { get; set; }

    public virtual User User { get; set; }
}