// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class InstructorProfile
{
    public int InstructorId { get; set; }

    public int UserId { get; set; }

    public string Headline { get; set; }

    public string Biography { get; set; }

    public string Website { get; set; }

    public string LinkedInProfile { get; set; }

    public string TwitterHandle { get; set; }

    public int? YearsOfExperience { get; set; }

    public int? TotalStudents { get; set; }

    public decimal? AverageRating { get; set; }

    public int? TotalCourses { get; set; }

    public virtual User User { get; set; }
}