// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class QuizAnswer
{
    public int AnswerId { get; set; }

    public int QuestionId { get; set; }

    public string AnswerText { get; set; }

    public bool? IsCorrect { get; set; }

    public int SortOrder { get; set; }

    public virtual QuizQuestion Question { get; set; }
}