// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Quiz
{
    public int QuizId { get; set; }

    public int LessonId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? TimeLimit { get; set; }

    public decimal? PassingScore { get; set; }

    public int? MaxAttempts { get; set; }

    public bool? IsRandomized { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual ICollection<QuizQuestion> QuizQuestions { get; set; } = new List<QuizQuestion>();

    public virtual ICollection<StudentQuizAttempt> StudentQuizAttempts { get; set; } = new List<StudentQuizAttempt>();
}