// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StudentQuizAttempt
{
    public int AttemptId { get; set; }

    public int UserId { get; set; }

    public int QuizId { get; set; }

    public int AttemptNumber { get; set; }

    public decimal? Score { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int? TimeSpent { get; set; }

    public bool? IsPassed { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual User User { get; set; }
}