// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StudentProgress
{
    public int ProgressId { get; set; }

    public int UserId { get; set; }

    public int LessonId { get; set; }

    public int CourseId { get; set; }

    public bool? IsCompleted { get; set; }

    public int? TimeSpent { get; set; }

    public DateTime? LastAccessedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual User User { get; set; }
}